name: Integration

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0

      - name: Install packages
        run: |
          npm install

      - name: Run lint
        run: |
          npm run lint:check

      - name: Run unit tests with coverage
        run: |
          npm run test:cov

      - name: Run build
        run: |
          npm run build
